version: "3.3"

services:

  directordb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=123456qw
      - POSTGRES_DB=director
    ports:
      - 5440

  customerdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=123456qw
      - POSTGRES_DB=customer
    ports:
      - 5441

  orderdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres3
      - POSTGRES_PASSWORD=123456qw
      - POSTGRES_DB=orders
    ports:
      - 5442


  directorServer:
    build: directorServer/
    image: director
    ports:
      - "8084:8084"
    depends_on:
      - directordb

  customerServer:
    build: customerServer/
    image: customer
    ports:
      - "8082:8082"
    depends_on:
      - customerdb

  orderServer:
    build: orderServer/
    image: order
    ports:
      - "8087:8087"
    depends_on:
      - orderdb

  mediator:
    build: server/
    ports:
      - "8083:8083"
    depends_on:
      - directorServer
      - customerServer
      - orderServer