apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-dep
  template:
    metadata:
      labels:
        app: server-dep
    spec:
      containers:
        - image: server-dep
          imagePullPolicy: IfNotPresent
          name: server-dep
          ports:
            - containerPort: 8083