apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverdoubled
spec:
  selector:
    matchLabels:
      app: serverdoubled
  replicas: 1
  template:
    metadata:
      labels:
        app: serverdoubled
    spec:
      containers:
        - name: serverdoubled
          image: flecv/serverdoubled:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
              name: serverdoubled